frase = "Curso em Vídeo Python"
print(frase)
print(frase[3:14])
print(frase[:12])
print(frase[:14])
print(frase[9::3])
print(frase[1:15:2])
print(frase[::2])
print(frase.count("o"))
print(len(frase))
print(frase.replace("Python" , "Android"))
print(frase.split())
dividido = frase.split()
print(dividido[2])
print(dividido[2][3])

